apiVersion: v1
kind: Service
metadata:
  name: camp-scout-service
  namespace: prod
spec:
  selector:
    app: camp-scout
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
