pipeline {
    agent any

    environment {
        PROJECT_ID = 'praks-dev'
        CLUSTER_NAME = 'prod-cluster'
        CLUSTER_ZONE = 'asia-south1-b'
        GOOGLE_APPLICATION_CREDENTIALS = credentials('jenkins-sa-key')  // Service account key file
        KUBE_CONFIG = 'kubeconfig'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from source repository
                git branch: 'master', url: 'https://github.com/praks7v/Camp-Scout.git'
            }
        }

        stage('Authenticate with GCP') {
            steps {
                script {
                    // Authenticate with Google Cloud
                    sh 'gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}'
                }
            }
        }

        stage('Get GKE Credentials') {
            steps {
                script {
                    // Fetch credentials to interact with GKE cluster
                    sh '''
                    gcloud container clusters get-credentials ${CLUSTER_NAME} \
                      --zone ${CLUSTER_ZONE} \
                      --project ${PROJECT_ID}
                    '''
                }
            }
        }

        stage('Deploy to GKE') {
            steps {
                script {
                                                   
                    // Deploy Kubernetes manifests using kubectl
                    sh '''
                    kubectl apply -f Manifests/prod-deployments.yml --namespace=prod
                    sleep 60
                    '''
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                script {
                    // Verify that the deployment is successful
                    sh '''
                    kubectl get pods --namespace=prod
                    kubectl get svc --namespace=prod
                    '''
                }
            }
        }
    }
}
