pipeline {
    agent any

    parameters {
        choice(name: 'DEPLOY_ENV', choices: ['blue', 'green'], description: 'Choose which environment to deploy: Blue or Green')
        choice(name: 'DOCKER_TAG', choices: ['blue', 'green'], description: 'Choose the Docker image tag for the deployment')
        booleanParam(name: 'SWITCH_TRAFFIC', defaultValue: false, description: 'Switch traffic between Blue and Green')
    }

    environment {
        PROJECT_ID = 'shopvory-ecommerce'
        CLUSTER_NAME = 'dev-cluster'
        CLUSTER_ZONE = 'us-east1-c'
        GOOGLE_APPLICATION_CREDENTIALS = credentials('jenkins-sa-key')  // Service account key file
        KUBE_CONFIG = 'kubeconfig'
        USE_GKE_GCLOUD_AUTH_PLUGIN = 'True'  // Set the environment variable for kubectl

        IMAGE_NAME = "praks007/camp-scout-prod"
        TAG = "${params.DOCKER_TAG}"  // The image tag now comes from the parameter
        KUBE_NAMESPACE = 'prod'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from source repository
                git branch: 'gcp-infra', url: 'https://github.com/praks7v/Camp-Scout.git'
            }
        }

        stage('Docker Pull & Tag') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh "docker pull praks007/camp-scout-dev:latest && docker tag praks007/camp-scout-dev:latest ${IMAGE_NAME}:${TAG}"
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image --format table -o trivy-is-report.json ${IMAGE_NAME}:${TAG}" 
            }
        }

        stage('Docker Push Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh "docker push ${IMAGE_NAME}:${TAG}"
                    }
                }
            }
        }

        stage('Authenticate with GCP') {
            steps {
                script {
                    // Authenticate with Google Cloud
                    sh 'gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}'
                }
            }
        }

        stage('Get GKE Credentials') {
            steps {
                script {
                    // Fetch credentials to interact with GKE cluster
                    sh '''
                    gcloud container clusters get-credentials ${CLUSTER_NAME} \
                      --zone ${CLUSTER_ZONE} \
                      --project ${PROJECT_ID}
                    '''
                }
            }
        }

        stage('Deploy Secret, Namespace and ServiceAccount') {
            steps {
                script {
                                                   
                    // Deploy Kubernetes manifests using kubectl
                    sh '''
                    kubectl apply -f Manifests/prod/prod-namespace.yml
                    kubectl apply -f Manifests/prod/prod-secret.yml --namespace=${KUBE_NAMESPACE}
                    kubectl apply -f Manifests/prod/prod-service-account.yml --namespace=${KUBE_NAMESPACE}
                    '''
                }
            }
        }
        
        stage('Deploy Service Camp-Scout') {
            steps {
                script {
                    
                    sh ''' 
                    if ! kubectl get svc camp-scout-service -n ${KUBE_NAMESPACE}; then
                        kubectl apply -f Manifests/prod/prod-service.yml -n ${KUBE_NAMESPACE}
                    fi
                    '''
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    def deploymentFile = ""
                    if (params.DEPLOY_ENV == 'blue') {
                        deploymentFile = 'Manifests/prod/prod-deployments-blue.yml'
                    } else {
                        deploymentFile = 'Manifests/prod/prod-deployments-green.yml'
                    }
        
                    // Apply the correct deployment file using proper string interpolation
                    sh """
                    kubectl apply -f ${deploymentFile} --namespace=${KUBE_NAMESPACE}
                    sleep 30
                    """
                }
            }
        }

        stage('Switch Traffic Between Blue & Green Environment') {
            when {
                expression { return params.SWITCH_TRAFFIC }
            }
            steps {
                script {
                    def newEnv = params.DEPLOY_ENV

                    // Always switch traffic based on DEPLOY_ENV
                    sh "kubectl patch service camp-scout-service -p '{\"spec\": {\"selector\": {\"app\": \"camp-scout\", \"version\": \"${newEnv}\"}}}' -n ${KUBE_NAMESPACE}"
                    echo "Traffic has been switched to the ${newEnv} environment."
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                script {
                    def verifyEnv = params.DEPLOY_ENV
                    
                    sh '''
                    kubectl get pods -l version=${verifyEnv} -n ${KUBE_NAMESPACE}
                    kubectl get svc camp-scout-service -n ${KUBE_NAMESPACE}
                    '''
                }
            }
        }
    }
}
