---
- name: Install Google Cloud SDK
  hosts: jenkins-vm
  become: true

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
        state: present

    - name: Add Google Cloud apt-key
      ansible.builtin.command: >
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      args:
        creates: /usr/share/keyrings/cloud.google.gpg

    - name: Add Google Cloud SDK repository to sources list
      ansible.builtin.copy:
        content: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main'
        dest: /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: Update APT package index after adding Google Cloud repository
      apt:
        update_cache: yes

    - name: Install Google Cloud CLI
      apt:
        name: google-cloud-cli
        state: present
