---
- name: Install SonarQube Docker Image and Run
  hosts: sonarqube-vm
  become: yes
  vars_files:
    - vars/sonarqube.yml
  tasks:
    - name: Pull SonarQube Docker image
      docker_image:
        name: "{{ sonarqube_image }}:{{ sonarqube_image_tag }}"
        source: pull

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: "{{ sonarqube_image }}:{{ sonarqube_image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ sonarqube_host_port }}:{{ sonarqube_container_port }}"      

    - name: Wait for SonarQube to be ready
      wait_for:
        port: "{{ sonarqube_host_port }}"
        delay: 10
        timeout: 300
        state: started